# Generated by Django 5.1.4 on 2024-12-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('office_staff', 'Office Staff'), ('librarian', 'Librarian')], max_length=50)),
            ],
        ),
    ]
